version: "3.9"

services:
  aichat-dev:
    image: aichat-dev
    build:
      context: .
      dockerfile: ./dockerfile/local/Dockerfile
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    ports:
      - "3000:5173"
    networks:
      - default
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

networks:
  default:
    driver: bridge
