version: "3.9"

services:
  aichat:
    image: aichat
    build:
      context: .
      dockerfile: ./dockerfile/prod/Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
    driver: bridge
